### PR TITLE
Update networks.json

### PR DESCRIPTION
**Pull request by Scrollsale**
please add Zetachain testnet Thanks in advance

### CODE REVIEW

**Comment by J94k** [comment]
@Scrollsale 
1. Please, make a proper format for JSON file. No spaces before or after a new network obejct.
2. Check this guide and add a logo: https://github.com/noxonsu/unifactory/blob/main/docs/addNetwork.md
3. Do you plan to add a mainnet? This is production environment so I don't see much point in just adding a testnet. It affects other clients.

**Comment by Scrollsale** [comment]
> @Scrollsale
> 
> 1. Please, make a proper format for JSON file. No spaces before or after a new network obejct.
> 2. Check this guide and add a logo: https://github.com/noxonsu/unifactory/blob/main/docs/addNetwork.md
> 3. Do you plan to add a mainnet? This is production environment so I don't see much point in just adding a testnet. It affects other clients.

yes i plan to add mainnet

**Comment by J94k** [comment]
So you add the mainnet with this change, don't you?
What do you mean by disabled? It's source code changes, you should be able to put in source files and update this MR.

**Comment by Scrollsale** [comment]
> So you add the mainnet with this change, don't you? What do you mean by disabled? It's source code changes, you should be able to put in source files and update this MR.

i didnt add mainnet yet, mainnet of Zetachain not launch yet

**Comment by J94k** [comment]
@Scrollsale so what's the point to add this new network in production environment?
If you want to use it in your personal project, just build the app from your repository.

**Comment by shendel** [comment]
Block merge
- json broken
- contracts are not verified
- Storage not vailid
- ExStorage not valid
- No blockchain icon
- Blockchain icon not specified in sources

**Pull request closed without merging**
